### ISSUE TITLE
convert doesn't find objects (__Broken_State__)

### ISSUE THREAD

**Issue by mejo-** [gocept/zodb.py3migrate#9]
Hi,

I tried to run the zodb-py3migrate-* scripts against a Data.fs from Zope2.13 that contains objects imported from an ancient Zope2.10 setup. While `analyze` detected several binary objects (mostly ISO-8859-15 encoded strings), `convert` fails to find them even though I'm pretty sure that I described them correctly in `convert.ini`:

```
# zodb-py3migrate-analyze Data.fs
WARNING:zodb.py3migrate.migrate:Analyzing about 3104 objects.
Found 8 binary fields: (number of occurrences)
OFS.DTMLDocument.DTMLDocument.__Broken_state__ is dict (2)
OFS.DTMLMethod.DTMLMethod.__Broken_state__ is dict (354)
OFS.Folder.Folder.__Broken_state__ is dict (1)
OFS.Image.File.__Broken_state__ is dict (21)
OFS.Image.Image.__Broken_state__ is dict (121)
OFS.Image.Pdata.__Broken_state__ is dict (18)
Products.PythonScripts.PythonScript.PythonScript.__Broken_state__ is dict (92)
Products.ZSQLMethods.SQL.SQL.__Broken_state__ is dict (2)
```

convert.ini:
```
[iso-8859-15]
OFS.DTMLMethod.DTMLMethod.__Broken_state__
```

```
# zodb-py3migrate-convert Data.fs --config=convert.ini 
WARNING:zodb.py3migrate.migrate:Analyzing about 3104 objects.
ERROR:zodb.py3migrate.migrate:Could not execute {'_vars': {}, 'title': '', 'raw': '<h3>Navigationsmen\xfc</h3>', 'globals': {}, '__name__': 'standard_iframe_footer', '__ac_local_roles__': {'stefan': ['Owner']}}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/zodb.py3migrate-0.6.dev0-py2.7.egg/zodb/py3migrate/migrate.py", line 150, in find_obj_with_binary_content
    yield obj, data, key, value, type_
GeneratorExit
Exception RuntimeError: 'generator ignored GeneratorExit' in <generator object find_obj_with_binary_content at 0x7f2c391d3be0> ignored
Traceback (most recent call last):
  File "/usr/local/bin/zodb-py3migrate-convert", line 11, in <module>
    load_entry_point('zodb.py3migrate==0.6.dev0', 'console_scripts', 'zodb-py3migrate-convert')()
  File "/usr/local/lib/python2.7/dist-packages/zodb.py3migrate-0.6.dev0-py2.7.egg/zodb/py3migrate/convert.py", line 72, in main
    run(parser, convert, 'config', 'verbose', args=args)
  File "/usr/local/lib/python2.7/dist-packages/zodb.py3migrate-0.6.dev0-py2.7.egg/zodb/py3migrate/migrate.py", line 238, in run
    return callable(storage, *callable_args)
  File "/usr/local/lib/python2.7/dist-packages/zodb.py3migrate-0.6.dev0-py2.7.egg/zodb/py3migrate/convert.py", line 60, in convert
    verb='Converted', verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/zodb.py3migrate-0.6.dev0-py2.7.egg/zodb/py3migrate/convert.py", line 28, in convert_storage
    data[key] = value.decode(encoding)
AttributeError: 'dict' object has no attribute 'decode'
```

So apparently the key with the wrong encoding is ['raw'].

Still, with the following `convert.ini`, nothing is found:

```
[iso-8859-15]
OFS.DTMLMethod.DTMLMethod.__Broken_state__['raw']
OFS.DTMLMethod.DTMLMethod.__Broken_state__.raw
```

```
# zodb-py3migrate-convert Data.fs --config=convert.ini -v
WARNING:zodb.py3migrate.migrate:Analyzing about 3104 objects.
Found 0 classes whose objects do not have __dict__: (number of occurrences)

# ########################################################### #

Converted 0 binary fields: (number of occurrences)
```

Any idea, what I'm missing? Is this related to the objects being `__Broken_State__`?

**Comment by icemac** [comment]
`zodb.py3migrate` needs access to the Python classes belonging to the objects you have stored in the ZODB.
I tried to make point 2 of the documentation a bit clearer, see https://zodbpy3migrate.readthedocs.io/doc.html#upgrade-workflow
